#!/usr/bin/env bash
# shellcheck disable=SC2086
# When passing domain and subdomain parameters, display information for the specified subdomain

domain=$1
subdo='www lb-01 web-01 web-02'
if (( $# == 2 ))
then
    subdo="$2"
fi

for sub in $subdo
do
    printf "The subdomain %s is a " "$sub"
    dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'
done
