#!/usr/bin/env bash
# Install nginx on your web-01 server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/share/nginx/html/index.html
sudo service nginx restart
