#!/usr/bin/env bash
# Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "35i\ $redirect" /etc/nginx/sites-available/default
sudo sed -i "35i\ $redirect" /etc/nginx/sites-enabled/default
sudo service nginx restart
