#!/usr/bin/env bash
# Install and configure HAproxy on load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*

f_end="\nfrontend haproxynode
		  tbind *:80
		  tdefault_backend back_nodes\n"
b_end="backend back_nodes\n\tbalance roundrobin
	       tserver 777-web-01 35.243.178.239 check
	       tserver 777-web-02 35.237.166.91 check\n"

echo -e $f_end | sudo tee --append /etc/haproxy/haproxy.cfg
echo -e $b_end | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
