#!/usr/bin/env bash
# pings an IP address passed as an argument 5 times
IPADDRESS=$1
if [ "$IPADDRESS" ]; then
    ping -c 5 "$IPADDRESS"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
