#!/usr/bin/env bash
# gives you information about the holbertonschool file.
hol=holbertonschool
if [ -e "$hol" ]
then
    echo "holbertonschool file exists"
    if [ -s "$hol" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$hol" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
    fi
